"""initial schema sync

Revision ID: 8646a35ef1a2
Revises: 
Create Date: 2026-08-14 09:41:25.026607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8646a35ef1a2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('category', sa.Enum('MATCH_REPORT', 'TRANSFER_RUMOUR', 'TRANSFER_OFFICIAL', 'PREVIEW', 'NEWS', 'ANALYSIS', name='newscategory'), nullable=False))
    op.add_column('articles', sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', 'ARCHIVED', name='articlestatus'), nullable=False))
    op.create_foreign_key(None, 'articles', 'users', ['author_id'], ['id'])
    op.add_column('match_events', sa.Column('player_on_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'match_events', 'players', ['player_on_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match_events', type_='foreignkey')
    op.drop_column('match_events', 'player_on_id')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'status')
    op.drop_column('articles', 'category')
    # ### end Alembic commands ###
